/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.patientRole;

import business.HealthCareSystem;
import business.drug.Drug;
import business.patient.experience.Experience;
import business.patient.experience.PatientExperience;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Deepthi
 */
public class PatientsWithSameDrugJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;     
    private HealthCareSystem system;
    private UserAccount userAccount;
    private Drug drug;
    /**
     * Creates new form PatientsWithSameDrugJPanel
     */
    public PatientsWithSameDrugJPanel(JPanel userProcessContainer,HealthCareSystem system,UserAccount userAccount,Drug drug) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.userAccount = userAccount;
        this.drug = drug;
        populateExperiences();
    }
    private void populateExperiences(){        
        //get the list of patientExperiences
         experienceJTextArea.setText("");
        for(PatientExperience patientExperience : system.getPatientExperienceList()){
            for(Experience experience : patientExperience.getExperienceList()){
                if((drug.getDrugName()) .equals(experience.getDrug()))
             experienceJTextArea.append(patientExperience.getPatientName().concat(" : ").concat(experience.getExperince().concat("\n")));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        experienceJTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        experienceJTextField = new javax.swing.JTextField();
        shareJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Share/View the experience of drug usage");

        experienceJTextArea.setBackground(new java.awt.Color(200, 224, 253));
        experienceJTextArea.setColumns(20);
        experienceJTextArea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        experienceJTextArea.setRows(5);
        jScrollPane1.setViewportView(experienceJTextArea);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Experience:");

        experienceJTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        shareJButton.setBackground(new java.awt.Color(137, 185, 239));
        shareJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        shareJButton.setText("Share Experience");
        shareJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shareJButtonActionPerformed(evt);
            }
        });

        backJButton.setBackground(new java.awt.Color(137, 185, 239));
        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/patientRole/patient3.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(470, 470, 470)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(shareJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel2)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(383, 383, 383)
                                .addComponent(experienceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(218, 218, 218))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(125, 125, 125)))
                        .addComponent(jLabel3)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel3)))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(experienceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(shareJButton)
                .addGap(29, 29, 29)
                .addComponent(backJButton)
                .addContainerGap(112, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void shareJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shareJButtonActionPerformed
        // TODO add your handling code here:
        String experience = experienceJTextField.getText();
        String  patientName = userAccount.getPerson().getFirstName();
        
        //Create  patient experience and add it to the system
        PatientExperience pe = new PatientExperience();
        pe.setPatientName(patientName);
        Experience e = new Experience();
        e.setDrug(drug.getDrugName());
        e.setExperince(experience);
        pe.getExperienceList().add(e);
        
        system.getPatientExperienceList().add(pe);
        populateExperiences();
    }//GEN-LAST:event_shareJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextArea experienceJTextArea;
    private javax.swing.JTextField experienceJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton shareJButton;
    // End of variables declaration//GEN-END:variables
}
