package com.me.care.model;

// Generated Apr 20, 2015 3:47:52 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Drug generated by hbm2java
 */
@Entity
@Table(name = "drug", catalog = "projectdb")
public class Drug implements java.io.Serializable {

	private String drugId;
	private String name;
	private String ingredients;
	private String usageDirections;
	private String warnings;
	private Set<Medication> medications = new HashSet<Medication>(0);

	public Drug() {
	}

	public Drug(String drugId) {
		this.drugId = drugId;
	}

	public Drug(String drugId, String name, String ingredients,
			String usageDirections, String warnings, Set<Medication> medications) {
		this.drugId = drugId;
		this.name = name;
		this.ingredients = ingredients;
		this.usageDirections = usageDirections;
		this.warnings = warnings;
		this.medications = medications;
	}

	@Id
	@Column(name = "drugId", unique = true, nullable = false, length = 45)
	public String getDrugId() {
		return this.drugId;
	}

	public void setDrugId(String drugId) {
		this.drugId = drugId;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Ingredients", length = 45)
	public String getIngredients() {
		return this.ingredients;
	}

	public void setIngredients(String ingredients) {
		this.ingredients = ingredients;
	}

	@Column(name = "UsageDirections", length = 45)
	public String getUsageDirections() {
		return this.usageDirections;
	}

	public void setUsageDirections(String usageDirections) {
		this.usageDirections = usageDirections;
	}

	@Column(name = "Warnings", length = 45)
	public String getWarnings() {
		return this.warnings;
	}

	public void setWarnings(String warnings) {
		this.warnings = warnings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "drug")
	public Set<Medication> getMedications() {
		return this.medications;
	}

	public void setMedications(Set<Medication> medications) {
		this.medications = medications;
	}

}
