package com.me.care.model;

// Generated Apr 20, 2015 3:47:52 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Workrequest generated by hbm2java
 */
@Entity
@Table(name = "workrequest", catalog = "projectdb")
public class Workrequest implements java.io.Serializable {

	private Integer requestId;
	private Integer assignedTo;
	private String status;
	private Date createdOn;
	private Integer patientId;

	public Workrequest() {
	}

	public Workrequest(Integer assignedTo, String status, Date createdOn,
			Integer patientId) {
		this.assignedTo = assignedTo;
		this.status = status;
		this.createdOn = createdOn;
		this.patientId = patientId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "requestId", unique = true, nullable = false)
	public Integer getRequestId() {
		return this.requestId;
	}

	public void setRequestId(Integer requestId) {
		this.requestId = requestId;
	}

	@Column(name = "AssignedTo")
	public Integer getAssignedTo() {
		return this.assignedTo;
	}

	public void setAssignedTo(Integer assignedTo) {
		this.assignedTo = assignedTo;
	}

	@Column(name = "Status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CreatedOn", length = 10)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "PatientId")
	public Integer getPatientId() {
		return this.patientId;
	}

	public void setPatientId(Integer patientId) {
		this.patientId = patientId;
	}

}
