/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.adminRole;

import business.enterprise.Enterprise;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Deepthi
 */
public class EnterpriseAdminWorkAreaJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form EnterpriseAdminWorkAreaJPanel
     */
    public EnterpriseAdminWorkAreaJPanel(JPanel userProcessContainer,Enterprise enterprise, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageOrganizationJButton = new javax.swing.JButton();
        manageUserJButton = new javax.swing.JButton();
        MangageEmployeeJButton = new javax.swing.JButton();
        managePersonInformationJButton = new javax.swing.JButton();
        resetPasswordJButton = new javax.swing.JButton();
        updateEnterpriseDetailsJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Enterprise Admin Work Area");

        manageOrganizationJButton.setBackground(new java.awt.Color(137, 185, 239));
        manageOrganizationJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageOrganizationJButton.setText("Manage Organizations >>");
        manageOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationJButtonActionPerformed(evt);
            }
        });

        manageUserJButton.setBackground(new java.awt.Color(137, 185, 239));
        manageUserJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageUserJButton.setText("Manage Users >>");
        manageUserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserJButtonActionPerformed(evt);
            }
        });

        MangageEmployeeJButton.setBackground(new java.awt.Color(137, 185, 239));
        MangageEmployeeJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        MangageEmployeeJButton.setText("Manage Employee >>");
        MangageEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MangageEmployeeJButtonActionPerformed(evt);
            }
        });

        managePersonInformationJButton.setBackground(new java.awt.Color(137, 185, 239));
        managePersonInformationJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        managePersonInformationJButton.setText("Manage Personal Information >>");
        managePersonInformationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePersonInformationJButtonActionPerformed(evt);
            }
        });

        resetPasswordJButton.setBackground(new java.awt.Color(137, 185, 239));
        resetPasswordJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resetPasswordJButton.setText("Reset Password >>");
        resetPasswordJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetPasswordJButtonActionPerformed(evt);
            }
        });

        updateEnterpriseDetailsJButton.setBackground(new java.awt.Color(137, 185, 239));
        updateEnterpriseDetailsJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updateEnterpriseDetailsJButton.setText("Update Enterprise Details >>");
        updateEnterpriseDetailsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEnterpriseDetailsJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(512, 512, 512)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(480, 480, 480)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(updateEnterpriseDetailsJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MangageEmployeeJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageOrganizationJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageUserJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(managePersonInformationJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resetPasswordJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(690, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(89, 89, 89)
                .addComponent(manageOrganizationJButton)
                .addGap(64, 64, 64)
                .addComponent(MangageEmployeeJButton)
                .addGap(52, 52, 52)
                .addComponent(manageUserJButton)
                .addGap(59, 59, 59)
                .addComponent(managePersonInformationJButton)
                .addGap(65, 65, 65)
                .addComponent(resetPasswordJButton)
                .addGap(67, 67, 67)
                .addComponent(updateEnterpriseDetailsJButton)
                .addGap(0, 168, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonActionPerformed
        // TODO add your handling code here:
        ManageOrganizationJPanel panel = new ManageOrganizationJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageOrganizationJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationJButtonActionPerformed

    private void manageUserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserJButtonActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel panel = new ManageUserAccountJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageUserAccountJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageUserJButtonActionPerformed

    private void MangageEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MangageEmployeeJButtonActionPerformed
        // TODO add your handling code here:
        ManageEmployeeJPanel panel = new ManageEmployeeJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("ManageEmployeeJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_MangageEmployeeJButtonActionPerformed

    private void managePersonInformationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePersonInformationJButtonActionPerformed
        // TODO add your handling code here:
         ManageAdminPersonalInformationJPanel panel = new ManageAdminPersonalInformationJPanel(userProcessContainer, enterprise,userAccount);
        userProcessContainer.add("ManageAdminPersonalInformationJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managePersonInformationJButtonActionPerformed

    private void updateEnterpriseDetailsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEnterpriseDetailsJButtonActionPerformed
        // TODO add your handling code here:UpdateEnterpiseDetailsJPanel
         UpdateEnterpiseDetailsJPanel panel = new UpdateEnterpiseDetailsJPanel(userProcessContainer, enterprise,userAccount);
        userProcessContainer.add("UpdateEnterpiseDetailsJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_updateEnterpriseDetailsJButtonActionPerformed

    private void resetPasswordJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPasswordJButtonActionPerformed
        // TODO add your handling code here:AdminResetPasswordJPanel
         AdminResetPasswordJPanel panel = new AdminResetPasswordJPanel(userProcessContainer, enterprise,userAccount);
        userProcessContainer.add("AdminResetPasswordJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_resetPasswordJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MangageEmployeeJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageOrganizationJButton;
    private javax.swing.JButton managePersonInformationJButton;
    private javax.swing.JButton manageUserJButton;
    private javax.swing.JButton resetPasswordJButton;
    private javax.swing.JButton updateEnterpriseDetailsJButton;
    // End of variables declaration//GEN-END:variables
}
