/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.doctorRole;

import business.HealthCareSystem;
import business.drug.Drug;
import business.enterprise.DrugCompanyEnterprise;
import business.enterprise.Enterprise;
import business.organization.DrugManagement;
import business.organization.Organization;
import business.patient.Patient;
import business.patient.adverseevents.AdverseEvent;
import business.useraccount.UserAccount;
import business.workqueue.DrugAdverseEventRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Deepthi
 */
public class AdverseEventOfPatientJPanel extends javax.swing.JPanel {
    
    private HealthCareSystem system;
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Organization organization;
    private UserAccount userAccount;
    private Patient patient;
    /**
     * Creates new form AdverseEventJPanel
     */
    public AdverseEventOfPatientJPanel(HealthCareSystem system,JPanel userProcessContainer, Enterprise enterprise, Organization organization, UserAccount userAccount,Patient patient) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = organization;
        this.userAccount = userAccount;
        this.system = system;
        this.patient = patient;
         populateDrugManufacturersComboBox();
    }

     private void populateDrugManufacturersComboBox(){
        drugManfJComboBox.removeAllItems();
        ArrayList<DrugCompanyEnterprise> drugCmpyList = system.getAllDrugCompanyEnterprisesInNetwork();
        for(DrugCompanyEnterprise drugCmpy : drugCmpyList){
            drugManfJComboBox.addItem(drugCmpy);
        }
    }
     private void populateDrugComboBox(DrugCompanyEnterprise drugCompanyEnterprise){
        drugJComboBox.removeAllItems();
        for(Drug drug : drugCompanyEnterprise.getDrugCatalogue().getDrugsList()){
            if(drug.isIsRemApproved()){
            drugJComboBox.addItem(drug);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adverseEffectJTextField = new javax.swing.JTextArea();
        drugManfJComboBox = new javax.swing.JComboBox();
        drugJComboBox = new javax.swing.JComboBox();
        reportJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Report An Adverse Event ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Select the Drug Manufacturer");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Select the Drug:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Adverse Effect:");

        adverseEffectJTextField.setColumns(20);
        adverseEffectJTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adverseEffectJTextField.setRows(5);
        jScrollPane1.setViewportView(adverseEffectJTextField);

        drugManfJComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        drugManfJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        drugManfJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugManfJComboBoxActionPerformed(evt);
            }
        });

        drugJComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        drugJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        reportJButton.setBackground(new java.awt.Color(137, 185, 239));
        reportJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reportJButton.setText("Report");
        reportJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportJButtonActionPerformed(evt);
            }
        });

        backJButton.setBackground(new java.awt.Color(137, 185, 239));
        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(401, 401, 401)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drugJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drugManfJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(492, 492, 492)
                            .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reportJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(591, 591, 591)
                            .addComponent(jLabel1))))
                .addContainerGap(548, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drugManfJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drugJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reportJButton)
                    .addComponent(backJButton))
                .addContainerGap(271, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void drugManfJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugManfJComboBoxActionPerformed
        // TODO add your handling code here:
        DrugCompanyEnterprise drugCompanyEnterprise = (DrugCompanyEnterprise)drugManfJComboBox.getSelectedItem();
        if(drugCompanyEnterprise != null){
            populateDrugComboBox(drugCompanyEnterprise);
        }
        
        
    }//GEN-LAST:event_drugManfJComboBoxActionPerformed

    private void reportJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportJButtonActionPerformed
        // TODO add your handling code here:
        DrugCompanyEnterprise drugCmpy = (DrugCompanyEnterprise)drugManfJComboBox.getSelectedItem();
        Drug drug = (Drug)drugJComboBox.getSelectedItem();
        String adverseEffect = adverseEffectJTextField.getText();
        if(drugCmpy == null || drug ==  null || adverseEffect.isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter values");
            return;
        }
        
        //place the adverseEventRequest in DrugManagement Organizaition of drug company
            for(Organization organization : drugCmpy.getOrganizationDirectory().getOrganizationList()){
            if(organization instanceof DrugManagement){
                DrugAdverseEventRequest daer = new DrugAdverseEventRequest();
                daer.setAdverseEvent(adverseEffect);
                daer.setSender(userAccount);
                daer.setDrug(drug);
                daer.setStatus("Pending");
                daer.setRequestId(new Random().nextInt(100));
                daer.setSenderHospital(enterprise.getName());
                organization.getWorkQueue().getWorkRequestList().add(daer);
            }
        }  
            //add to adverse history of patient.
          AdverseEvent ae =  patient.getAdverseEventHistory().addAdverseEvent();
          ae.setAdverseEvent(adverseEffect);
          ae.setDrug(drug);
          JOptionPane.showMessageDialog(null, "Successfully reported to the manufacturer.");
    }//GEN-LAST:event_reportJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
          userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea adverseEffectJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox drugJComboBox;
    private javax.swing.JComboBox drugManfJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reportJButton;
    // End of variables declaration//GEN-END:variables
}
