/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.doctorRole;

import business.HealthCareSystem;
import business.enterprise.DrugCompanyEnterprise;
import business.enterprise.Enterprise;
import business.organization.DrugManagement;
import business.organization.Organization;
import business.useraccount.UserAccount;
import business.workqueue.AdverseEventRequest;
import business.workqueue.DrugAdverseEventRequest;
import business.workqueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Font;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Deepthi
 */
public class ProcessAdverseEventsJPanel extends javax.swing.JPanel {
      private HealthCareSystem system;
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Organization organization;
    private UserAccount userAccount;
    /**
     * Creates new form ProcessAdverseEventsJPanel
     */
    public ProcessAdverseEventsJPanel(HealthCareSystem system,JPanel userProcessContainer, Enterprise enterprise, Organization organization, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = organization;
        this.userAccount = userAccount;
        this.system = system;
        populateTable();
    }
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) adverseEventJTable.getModel();
        model.setRowCount(0);
        adverseEventJTable.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 18));

        for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof AdverseEventRequest) {
                Object[] row = new Object[7];
                row[0] = wr;
                row[1] = wr.getSender().getPerson().getFirstName();
                row[2] = ((AdverseEventRequest) wr).getDrugCompanyEnterprise();
                row[3] = ((AdverseEventRequest) wr).getDrug();
                row[4] = ((AdverseEventRequest) wr).getAdverseEvent();
                row[5] = wr.getStatus();
                row[6] = ((AdverseEventRequest) wr).getResult();
                model.addRow(row);

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        adverseEventJTable = new javax.swing.JTable();
        reportToManufacturerJButton = new javax.swing.JButton();
        rejectJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        adverseEventJTable.setBackground(new java.awt.Color(216, 217, 223));
        adverseEventJTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adverseEventJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request ID", "Sender", "Drug Manufacture", "Drug Name", "Adverse Event", "Status", "Result"
            }
        ));
        jScrollPane1.setViewportView(adverseEventJTable);

        reportToManufacturerJButton.setBackground(new java.awt.Color(137, 185, 239));
        reportToManufacturerJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reportToManufacturerJButton.setText("Report to Manufacturer ");
        reportToManufacturerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportToManufacturerJButtonActionPerformed(evt);
            }
        });

        rejectJButton.setBackground(new java.awt.Color(137, 185, 239));
        rejectJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rejectJButton.setText("Reject Request");
        rejectJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectJButtonActionPerformed(evt);
            }
        });

        backJButton.setBackground(new java.awt.Color(137, 185, 239));
        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Process Adverse Events");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(reportToManufacturerJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(303, 303, 303)
                                .addComponent(rejectJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1476, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(628, 628, 628)
                        .addComponent(jLabel1)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reportToManufacturerJButton)
                    .addComponent(rejectJButton))
                .addGap(140, 140, 140)
                .addComponent(backJButton)
                .addContainerGap(250, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reportToManufacturerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportToManufacturerJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = adverseEventJTable.getSelectedRow();
        if(selectedRow <0 ){
            JOptionPane.showMessageDialog(null, "Select the adverse event request");
            return;
        }
        
        AdverseEventRequest aer = (AdverseEventRequest)adverseEventJTable.getValueAt(selectedRow, 0);
        if(aer.getStatus().equals("Completed")){
             JOptionPane.showMessageDialog(null, "Request is already completed.");
            return;
        }
        DrugCompanyEnterprise drugCompanyEnterprise = aer.getDrugCompanyEnterprise();
        for(Organization organization : drugCompanyEnterprise.getOrganizationDirectory().getOrganizationList()){
            if(organization instanceof DrugManagement){
                DrugAdverseEventRequest daer = new DrugAdverseEventRequest();
                daer.setAdverseEvent(aer.getAdverseEvent());
                daer.setSender(userAccount);
                daer.setDrug(aer.getDrug());
                daer.setStatus("Pending");
                daer.setRequestId(new Random().nextInt(100));
                daer.setSenderHospital(enterprise.getName());
                organization.getWorkQueue().getWorkRequestList().add(daer);
            }
        }
        
        aer.setStatus("Completed");
        aer.setResult("Reported to Drug Company");
        
        populateTable();
        
    }//GEN-LAST:event_reportToManufacturerJButtonActionPerformed

    private void rejectJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = adverseEventJTable.getSelectedRow();
        if(selectedRow <0 ){
            JOptionPane.showMessageDialog(null, "Select the adverse event request");
            return;
        }
                AdverseEventRequest aer = (AdverseEventRequest)adverseEventJTable.getValueAt(selectedRow, 0);
                 if(aer.getStatus().equals("Completed")){
                    JOptionPane.showMessageDialog(null, "Request is already completed.");
                    return;
                }
                aer.setStatus("Completed");
                aer.setResult("Not an Adverse Effect");
                populateTable();
    }//GEN-LAST:event_rejectJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable adverseEventJTable;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rejectJButton;
    private javax.swing.JButton reportToManufacturerJButton;
    // End of variables declaration//GEN-END:variables
}
