/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.doctorRole;

import business.HealthCareSystem;
import business.enterprise.Enterprise;
import business.organization.DoctorOrganization;
import business.organization.Organization;
import business.patient.Patient;
import business.patient.adverseevents.AdverseEvent;
import business.patient.allergy.Allergy;
import business.patient.encounter.Encounter;
import business.patient.encounter.Medication;
import business.patient.encounter.VitalSign;
import business.patient.labtest.LabTest;
import business.useraccount.UserAccount;
import business.validation.ValidationUtil;
import business.workqueue.AppointmentRequest;
import business.workqueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Deepthi
 */
public class ViewEmergencyPatientHistoryJPanel extends javax.swing.JPanel {

    private HealthCareSystem system;
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Organization organization;
    private UserAccount userAccount;
    private Patient patient;
    private ArrayList<Encounter> completeEncounterList;
    private ArrayList<Allergy> completeAllergyList;
    private ArrayList<AdverseEvent> completeAdverseList;
        private ArrayList<LabTest> completeLabTestList;

    /**
     * Creates new form SearchPatientJPanel
     */
    public ViewEmergencyPatientHistoryJPanel(HealthCareSystem system, JPanel userProcessContainer, Enterprise enterprise, Organization organization, UserAccount userAccount,
            Patient patient,ArrayList<Encounter> completeEncounterList,  ArrayList<Allergy> completeAllergyList,ArrayList<AdverseEvent> completeAdverseList,
             ArrayList<LabTest> completeLabTestList) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = organization;
        this.userAccount = userAccount;
        this.system = system;
        this.patient = patient;
        this.completeEncounterList = completeEncounterList;
        this.completeAllergyList = completeAllergyList;
        this.completeAdverseList = completeAdverseList;
        this.completeLabTestList = completeLabTestList;
        populateFields();
        populateEncounterTable();
        populateVitalSignTable();
        populateMedicinesTable();
        populateStatusComboBox();
        populateAllergyTable();
        populateAdverseTable();
        populateLabTestTable();
        
        allergyJTable.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 18));
        encounterHistoryJTable.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 18));
        medicinesJTable.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 18));
        adverseEventsJTable.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 18));
                labTestJTable.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 18));


    }
    
    private void populateFields(){
        firstNameJTextField.setText(patient.getFirstName());
        lastNameJTextField.setText(patient.getLastName());
        ssnJTextField.setText(patient.getSsn());
        dobJTextField.setText(ValidationUtil.formatDate(patient.getDateOfBirth()));
    }
    
    private void populateStatusComboBox(){
         statusJComboBox.removeAllItems();
        statusJComboBox.addItem("ACTIVE");
        statusJComboBox.addItem("INACTIVE");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        encounterHistoryJTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        adverseEventsJTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        addEncounterJButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        allergyJTable = new javax.swing.JTable();
        statusJComboBox = new javax.swing.JComboBox();
        refreshAllergyJButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        medicinesJTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        vitalSignTableJTable = new javax.swing.JTable();
        encounterRefreshJButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        firstNameJTextField = new javax.swing.JTextField();
        saveJButton = new javax.swing.JButton();
        lastNameJTextField = new javax.swing.JTextField();
        ssnJTextField = new javax.swing.JTextField();
        dobJTextField = new javax.swing.JTextField();
        addAllergyJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        labTestJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        labTestJTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Allergy History");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Encounter History");

        encounterHistoryJTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        encounterHistoryJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Encounter Date", "Hospital", "Location", "Symptoms", "Diagonized Problem "
            }
        ));
        jScrollPane2.setViewportView(encounterHistoryJTable);

        adverseEventsJTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adverseEventsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Drug", "Adverse Events"
            }
        ));
        jScrollPane3.setViewportView(adverseEventsJTable);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Medication History");

        addEncounterJButton.setBackground(new java.awt.Color(137, 185, 239));
        addEncounterJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addEncounterJButton.setText("Add Encounter");
        addEncounterJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEncounterJButtonActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(137, 185, 239));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("Report Adverse Events");

        allergyJTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        allergyJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Information", "Status"
            }
        ));
        jScrollPane5.setViewportView(allergyJTable);

        statusJComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        statusJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        refreshAllergyJButton.setBackground(new java.awt.Color(137, 185, 239));
        refreshAllergyJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        refreshAllergyJButton.setText("Refresh");
        refreshAllergyJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshAllergyJButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Vital Sign History");

        medicinesJTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        medicinesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Encounter Date", "Drug", "Usage information", "Warnings"
            }
        ));
        jScrollPane6.setViewportView(medicinesJTable);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Adverse Events ");

        vitalSignTableJTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vitalSignTableJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Encounter Date", "Heart Rate", "Respiratory Rate", "Blood Pressure", "Weight"
            }
        ));
        jScrollPane7.setViewportView(vitalSignTableJTable);
        if (vitalSignTableJTable.getColumnModel().getColumnCount() > 0) {
            vitalSignTableJTable.getColumnModel().getColumn(0).setResizable(false);
            vitalSignTableJTable.getColumnModel().getColumn(1).setResizable(false);
            vitalSignTableJTable.getColumnModel().getColumn(2).setResizable(false);
            vitalSignTableJTable.getColumnModel().getColumn(3).setResizable(false);
        }

        encounterRefreshJButton.setBackground(new java.awt.Color(137, 185, 239));
        encounterRefreshJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        encounterRefreshJButton.setText("Refresh");
        encounterRefreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encounterRefreshJButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("First Name:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Last Name:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("SSN:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Date Of Birth :");

        firstNameJTextField.setEditable(false);
        firstNameJTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        saveJButton.setBackground(new java.awt.Color(137, 185, 239));
        saveJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        saveJButton.setText("Update Allergy Status");
        saveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButtonActionPerformed(evt);
            }
        });

        lastNameJTextField.setEditable(false);
        lastNameJTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        ssnJTextField.setEditable(false);
        ssnJTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        dobJTextField.setEditable(false);
        dobJTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        addAllergyJButton.setBackground(new java.awt.Color(137, 185, 239));
        addAllergyJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addAllergyJButton.setText("Add Allergy");
        addAllergyJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAllergyJButtonActionPerformed(evt);
            }
        });

        backJButton.setBackground(new java.awt.Color(137, 185, 239));
        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        labTestJButton.setBackground(new java.awt.Color(137, 185, 239));
        labTestJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labTestJButton.setText("Add Lab Tests");
        labTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labTestJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Lab Tests");

        labTestJTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labTestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "WBC", "RBC", "LDL", "HDL"
            }
        ));
        jScrollPane1.setViewportView(labTestJTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(encounterRefreshJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(refreshAllergyJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(268, 268, 268)
                                        .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(saveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statusJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(284, 284, 284)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel9)))
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstNameJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(lastNameJTextField)
                            .addComponent(ssnJTextField)
                            .addComponent(dobJTextField))
                        .addGap(205, 205, 205)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labTestJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                            .addComponent(addEncounterJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addAllergyJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(751, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(addEncounterJButton)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addAllergyJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ssnJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dobJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(firstNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labTestJButton)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(encounterRefreshJButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel6)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(refreshAllergyJButton))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(saveJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backJButton)
                .addContainerGap(218, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void populateAllergyTable(){
      DefaultTableModel model = (DefaultTableModel) allergyJTable.getModel();
        model.setRowCount(0);
        allergyJTable.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 18));
          for (Allergy allergy : completeAllergyList) {
            Object[] row = new Object[3];
            row[0] = allergy;
            row[1] = allergy.getAllergyInformation();
            row[2] = allergy.getStatus();
            model.addRow(row);
        }

        
    }
     private void populateAdverseTable(){
      DefaultTableModel model = (DefaultTableModel) adverseEventsJTable.getModel();
        model.setRowCount(0);
        allergyJTable.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 18));
          for (AdverseEvent adverseEvent : completeAdverseList) {
            Object[] row = new Object[2];
            row[0] = adverseEvent.getDrug();
            row[1] = adverseEvent.getAdverseEvent();
            model.addRow(row);
        }

        
    }
      private void populateLabTestTable() {
        DefaultTableModel model = (DefaultTableModel) labTestJTable.getModel();
        model.setRowCount(0);
        labTestJTable.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 18));
        for (LabTest labTest : completeLabTestList) {
            Object[] row = new Object[5];
            row[0] = labTest.getDate();
            row[1] = labTest.getWbc();
            row[2] = labTest.getRbc();
            row[3] = labTest.getlDL();
            row[4] = labTest.gethDL();
            model.addRow(row);
        }
    }
     
    private void populateEncounterTable(){
         DefaultTableModel model = (DefaultTableModel) encounterHistoryJTable.getModel();
            model.setRowCount(0);
        if(patient != null){
            for(Encounter encounter :completeEncounterList){
                Object[] row = new Object[5];
                row[0] =  encounter;
                row[1] = encounter.getHospitalName();
                row[2] = encounter.getHospitalLocation();
                row[2] = encounter.getSymptoms();
                row[3] = encounter.getDiagonizedDisease();
                model.addRow(row);
 
            }
        }
    }
    
    
    private void populateVitalSignTable(){
         DefaultTableModel model = (DefaultTableModel) vitalSignTableJTable.getModel();
            model.setRowCount(0);
             if(patient != null){
            for(Encounter encounter :completeEncounterList){
                VitalSign vitalSign =  encounter.getVitalSign();
                Object[] row = new Object[5];
                row[0] =  encounter;
                row[1] = vitalSign.getHeartRate();
                row[2] = vitalSign.getRespiratoryRate();
                row[3] = vitalSign.getSystolicBloodPressure();
                row[4] = vitalSign.getWeight();

                model.addRow(row);
 
            }
        }
    }
    
      private void populateMedicinesTable(){
         DefaultTableModel model = (DefaultTableModel) medicinesJTable.getModel();
            model.setRowCount(0);
             if(patient != null){
            for(Encounter encounter :completeEncounterList){
                for(Medication medication : encounter.getMedicationList()){
                Object[] row = new Object[4];
                row[0] = encounter;
                row[1] =  medication.getDrug().getDrugName();
                row[2] =  medication.getDrug().getUsageDirections();
                row[3] = medication.getDrug().getWarnings();
                model.addRow(row);
                }
            }
        }
    }
    
    private void addEncounterJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEncounterJButtonActionPerformed
        // TODO add your handling code here:
     
         AddEncounterJPanel panel = new AddEncounterJPanel(system,userProcessContainer,enterprise,userAccount, patient,completeEncounterList);
        userProcessContainer.add("AddEncounterJPanel", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addEncounterJButtonActionPerformed

    private void encounterRefreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encounterRefreshJButtonActionPerformed
        // TODO add your handling code here:
        populateEncounterTable();
        populateVitalSignTable();
        populateMedicinesTable();
        
    }//GEN-LAST:event_encounterRefreshJButtonActionPerformed

    private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = allergyJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a allergy");
            return;
        }
        Allergy allergy = (Allergy) allergyJTable.getValueAt(selectedRow, 0);
        String status = (String) statusJComboBox.getSelectedItem();
        allergy.setStatus(status);
        JOptionPane.showMessageDialog(null, "Successfully changed the status");

        populateAllergyTable();
    }//GEN-LAST:event_saveJButtonActionPerformed

    private void addAllergyJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAllergyJButtonActionPerformed
        // TODO add your handling code here:
        AddAllergyJPanel panel = new AddAllergyJPanel(userProcessContainer,patient,completeAllergyList);
        userProcessContainer.add("AddAllergyJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addAllergyJButtonActionPerformed

    private void refreshAllergyJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshAllergyJButtonActionPerformed
        // TODO add your handling code here:
        populateAllergyTable();
    }//GEN-LAST:event_refreshAllergyJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
            userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void labTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labTestJButtonActionPerformed
        // TODO add your handling code here:
         AddLabTestJPanel panel = new AddLabTestJPanel(system,userProcessContainer,enterprise,organization, userAccount,patient);
        userProcessContainer.add("AddLabTestJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_labTestJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAllergyJButton;
    private javax.swing.JButton addEncounterJButton;
    private javax.swing.JTable adverseEventsJTable;
    private javax.swing.JTable allergyJTable;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField dobJTextField;
    private javax.swing.JTable encounterHistoryJTable;
    private javax.swing.JButton encounterRefreshJButton;
    private javax.swing.JTextField firstNameJTextField;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JButton labTestJButton;
    private javax.swing.JTable labTestJTable;
    private javax.swing.JTextField lastNameJTextField;
    private javax.swing.JTable medicinesJTable;
    private javax.swing.JButton refreshAllergyJButton;
    private javax.swing.JButton saveJButton;
    private javax.swing.JTextField ssnJTextField;
    private javax.swing.JComboBox statusJComboBox;
    private javax.swing.JTable vitalSignTableJTable;
    // End of variables declaration//GEN-END:variables
}
