/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.pharmacistRole;

import business.HealthCareSystem;
import business.drug.Drug;
import business.enterprise.Enterprise;
import business.enterprise.PharmacyEnterprise;
import business.inventory.InventoryItem;
import business.organization.Organization;
import business.useraccount.UserAccount;
import business.workqueue.RollbackWorkRequest;
import business.workqueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Deepthi
 */
public class ManageRollbackRequestsJPanel extends javax.swing.JPanel {
 private HealthCareSystem system;
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Organization organization;
    private UserAccount userAccount;
    /**
     * Creates new form ManageRollbackRequestsJPanel
     */
    public ManageRollbackRequestsJPanel(HealthCareSystem system, JPanel userProcessContainer, Enterprise enterprise, Organization organization, UserAccount userAccount) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = organization;
        this.userAccount = userAccount;
        this.system = system;
        populateTable();
    }
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) rollbackJTable.getModel();
        model.setRowCount(0);
        rollbackJTable.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 18));

        for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof RollbackWorkRequest) {
                Object[] row = new Object[6];
                row[0] = ((RollbackWorkRequest) wr);
                row[1] = wr.getMessage();
                row[2] = wr.getSender().getPerson().getFirstName();
                row[3] = ((RollbackWorkRequest) wr).getSenderEnterprise();
                row[4] = ((RollbackWorkRequest) wr).getDrug();
                row[5] = wr.getStatus();
                model.addRow(row);

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        rollbackJTable = new javax.swing.JTable();
        rollbackJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        rollbackJTable.setBackground(new java.awt.Color(204, 224, 253));
        rollbackJTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rollbackJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "RequestID", "Message", "Sender", "Drug Company", "Drug", "Status"
            }
        ));
        jScrollPane1.setViewportView(rollbackJTable);

        rollbackJButton.setBackground(new java.awt.Color(137, 185, 239));
        rollbackJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rollbackJButton.setText("Rollback");
        rollbackJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollbackJButtonActionPerformed(evt);
            }
        });

        backJButton.setBackground(new java.awt.Color(137, 185, 239));
        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("RollBack Requests From Manufacturer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(328, 328, 328)
                        .addComponent(rollbackJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1422, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(591, 591, 591)
                        .addComponent(jLabel1)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rollbackJButton)
                    .addComponent(backJButton))
                .addContainerGap(430, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void rollbackJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollbackJButtonActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = rollbackJTable.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "please select the request to rollback the drug");
            return;
        }
        
        RollbackWorkRequest rwr = (RollbackWorkRequest)rollbackJTable.getValueAt(selectedRow, 0);
        
        Drug drug = rwr.getDrug();
        for(InventoryItem inventoryItem :((PharmacyEnterprise) enterprise).getInventory().getInventoryList() ){
            if((inventoryItem.getDrug().getDrugName()).equals(drug.getDrugName())){
                inventoryItem.setQuantity(0);
            }
        }
          JOptionPane.showMessageDialog(null, "Successfully rollbacked the drug");
          rwr.setStatus("Completed");
          populateTable();
    }//GEN-LAST:event_rollbackJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rollbackJButton;
    private javax.swing.JTable rollbackJTable;
    // End of variables declaration//GEN-END:variables
}
