/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.pharmacistRole;

import business.HealthCareSystem;
import business.email.Email;
import business.enterprise.Enterprise;
import business.organization.Organization;
import business.patient.Patient;
import business.patient.encounter.Medication;
import business.useraccount.UserAccount;
import business.workqueue.PrescriptionRequest;
import com.lowagie.text.Document;
import com.lowagie.text.Font;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfContentByte;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.CardLayout;
import java.awt.Graphics2D;
import java.awt.Shape;
import java.io.FileOutputStream;
import java.security.Security;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Deepthi
 */
public class OrderJPanel extends javax.swing.JPanel {
private HealthCareSystem system;
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Organization organization;
    private UserAccount userAccount;
    private PrescriptionRequest prescriptionRequest;
    /**
     * Creates new form OrderJPanel
     */
    public OrderJPanel(HealthCareSystem system, JPanel userProcessContainer, Enterprise enterprise, Organization organization, UserAccount userAccount,PrescriptionRequest prescriptionRequest) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = organization;
        this.userAccount = userAccount;
        this.system = system;
        this.prescriptionRequest = prescriptionRequest;
        populateFields();
        populateTable();
        
    }

    private void populateFields(){
        Patient patient = prescriptionRequest.getPatient();
        nameJLabel.setText(patient.getFirstName());
        emailJLabel.setText(patient.getEmailId());
        phoneNumberJLabel.setText(String.valueOf(patient.getPhoneNumber()));
        hospitalJLabel.setText(prescriptionRequest.getSenderHospital());
        hospitalAddressJLabel.setText(prescriptionRequest.getSenderHospitalAddress());
    }
    
    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) orderJTable.getModel();
        model.setRowCount(0);
        orderJTable.getTableHeader().setFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 18));

        ArrayList<Medication> medicinesList = prescriptionRequest.getMedicinesList();
        if (medicinesList != null) {
            for (Medication medication : medicinesList) {
                Object[] row = new Object[3];
                row[0] = medication.getDrug().getDrugModelNo();
                row[1] = medication.getDrug().getDrugName();
                row[2] = medication.getDosage();
                model.addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderJTable = new javax.swing.JTable();
        nameJLabel = new javax.swing.JLabel();
        emailJLabel = new javax.swing.JLabel();
        phoneNumberJLabel = new javax.swing.JLabel();
        hospitalJLabel = new javax.swing.JLabel();
        hospitalAddressJLabel = new javax.swing.JLabel();
        deliverJButton = new javax.swing.JButton();
        printJButton = new javax.swing.JButton();
        emailJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Prescription Details:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Patient Name :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Email ID:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Phone Number:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Hospital :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Address:");

        orderJTable.setBackground(new java.awt.Color(204, 224, 253));
        orderJTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        orderJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "BatchId", "DrugName", "Dosage"
            }
        ));
        jScrollPane1.setViewportView(orderJTable);

        nameJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameJLabel.setText("jLabel8");

        emailJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailJLabel.setText("jLabel9");

        phoneNumberJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phoneNumberJLabel.setText("jLabel10");

        hospitalJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hospitalJLabel.setText("jLabel8");

        hospitalAddressJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hospitalAddressJLabel.setText("jLabel9");

        deliverJButton.setBackground(new java.awt.Color(137, 185, 239));
        deliverJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deliverJButton.setText("Deliver Order");
        deliverJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliverJButtonActionPerformed(evt);
            }
        });

        printJButton.setBackground(new java.awt.Color(137, 185, 239));
        printJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        printJButton.setText("Print Order");
        printJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printJButtonActionPerformed(evt);
            }
        });

        emailJButton.setBackground(new java.awt.Color(137, 185, 239));
        emailJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailJButton.setText("Email Order");
        emailJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailJButtonActionPerformed(evt);
            }
        });

        backJButton.setBackground(new java.awt.Color(137, 185, 239));
        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneNumberJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(282, 282, 282)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(hospitalAddressJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hospitalJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deliverJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(backJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(91, 91, 91)
                        .addComponent(printJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137)
                        .addComponent(emailJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(529, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(nameJLabel)
                    .addComponent(hospitalJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(emailJLabel)
                    .addComponent(hospitalAddressJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(phoneNumberJLabel))
                .addGap(68, 68, 68)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deliverJButton)
                    .addComponent(printJButton)
                    .addComponent(emailJButton))
                .addGap(76, 76, 76)
                .addComponent(backJButton)
                .addContainerGap(178, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deliverJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliverJButtonActionPerformed
        // TODO add your handling code here:
        ArrayList<Medication> medicinesList = prescriptionRequest.getMedicinesList();
        if(medicinesList != null){
            prescriptionRequest.setStatus("Completed");
            JOptionPane.showMessageDialog(null, "Successfully completed the order");
            return;
        }
    }//GEN-LAST:event_deliverJButtonActionPerformed

    private void printJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printJButtonActionPerformed
        // TODO add your handling code here:
         Document document = new Document();
            try {
                JOptionPane.showMessageDialog(null, "Prescription printed");
            PdfWriter writer = PdfWriter.getInstance(document, 
                new FileOutputStream("PharmacyPrescription.pdf"));
            document.open();
            document.addTitle("Medical Prescription");
          //  document.addAuthor(staff.getPerson().getFirstName()+" "+staff.getPerson().getLastName());
            Paragraph p = new Paragraph("Medicines Prescribed");
            
            document.add(p);
            PdfContentByte cb = writer.getDirectContent();
            cb.saveState();
            Graphics2D g2 = cb.createGraphicsShapes(800, 500);
            Shape oldClip = g2.getClip();
            g2.clipRect(0, 0, 800, 500);
            Font font = new Font();
            font.setSize(0.5f);
            
            nameJLabel.print(g2);
            emailJLabel.print(g2);
            phoneNumberJLabel.print(g2);
            orderJTable.print(g2);
            g2.setClip(oldClip);
            g2.dispose();
            cb.restoreState();
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error creating file");
            }

            document.close();
    }//GEN-LAST:event_printJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void emailJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailJButtonActionPerformed
        // TODO add your handling code here:
         String mailtoEmail = JOptionPane.showInputDialog("ENTER THE RECEPIENT'S MAIL ID");
        String subject = JOptionPane.showInputDialog("ENTER THE SUBJECT");
       String  message = JOptionPane.showInputDialog("ENTER THE MESSAGE");
        Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());

        try {
            new Email().sendSSLMessage(mailtoEmail, subject, message, mailtoEmail);
        } catch (Exception ex) {
            System.out.println("Security Enabled");
        }
        JOptionPane.showMessageDialog(null, "Successfully mailed the precautions/Advice to patient");
        
    }//GEN-LAST:event_emailJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton deliverJButton;
    private javax.swing.JButton emailJButton;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JLabel hospitalAddressJLabel;
    private javax.swing.JLabel hospitalJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JTable orderJTable;
    private javax.swing.JLabel phoneNumberJLabel;
    private javax.swing.JButton printJButton;
    // End of variables declaration//GEN-END:variables
}
